#!/bin/sh -e

PACKAGE_VERSION=`dpkg-parsechangelog | grep ^Version: | cut -d\  -f2`
VERSION=`echo $PACKAGE_VERSION | cut -d- -f1`
VERSION_MAJOR=`echo $VERSION | cut -d. -f1-2`
TARBALL=.mysql-cluster-${VERSION}.tar.gz
URL=http://dev.mysql.com/get/Downloads/MySQL-Cluster-${VERSION_MAJOR}/mysql-cluster-gpl-${VERSION}.tar.gz/from/http://www.mirrorservice.org/sites/ftp.mysql.com/
DIR=mysql-cluster-${VERSION}

# Use ccache if available
if [ `which ccache` ]
then
	export MYSQL_BUILD_CC="ccache gcc"
	export MYSQL_BUILD_CXX="ccache g++"
fi

# Build test options
# nocheck - skip testing (faster build)
# fulltest - very long testsuite
# leave both commented out for the normal test
#export DEB_BUILD_OPTIONS=nocheck
#export DEB_BUILD_OPTIONS=fulltest

# Download original source code
if [ ! -f ${TARBALL} ]
then
	wget -O ${TARBALL} ${URL}
fi

# Remove any old copies of packages
rm -rf *.deb *.changes *.log

# Extract archive, add debian files
rm -rf ${DIR}
mkdir ${DIR}
tar -C ${DIR} --strip-components=1 -zxf ${TARBALL}
cp -arv debian ${DIR}

# Compile packages
cd ${DIR}
dpkg-buildpackage -b 2>&1 | tee build.log
cd ..

# Lintian checks
#lintian -c *.deb 2>&1 | tee lintian.log

# Cleanup and done
echo Done

