#!/bin/sh -e

VERSION_MAJOR=7.2
VERSION=7.2.4
TARBALL=.mysql-cluster-${VERSION}.tar.gz
URL=http://dev.mysql.com/get/Downloads/MySQL-Cluster-${VERSION_MAJOR}/mysql-cluster-gpl-${VERSION}.tar.gz/from/http://www.mirrorservice.org/sites/ftp.mysql.com/
DIR=mysql-cluster-${VERSION}
ORIG_DIR=${DIR}.orig

# Download original source code
if [ ! -f ${TARBALL} ]
then
	wget -O ${TARBALL} ${URL}
fi

# Extract archive, add debian files
rm -rf ${ORIG_DIR} ${DIR}
mkdir ${ORIG_DIR}
tar -C ${ORIG_DIR} --strip-components=1 -zxf ${TARBALL}
cp -arv ${ORIG_DIR} ${DIR}
cp -arv debian ${DIR}

# Generate diff
set -e
diff -urNad ${ORIG_DIR} ${DIR} | gzip -9 > mysql-cluster-${VERSION_MAJOR}_${VERSION}-0.1.patch.gz
set +e

# Cleanup
rm -rf ${ORIG_DIR} ${DIR}

