#!/bin/sh -e

apt-get update

apt-get -y install \
	libmysqld-cluster-pic \
	libmysqld-cluster-dev \
	libmysqlclient18-dev \
	libndbclient-dev \
	mysql-client-cluster \
	mysql-cluster-client \
	mysql-cluster-server-datanode \
	mysql-cluster-server-mgmtnode \
	mysql-cluster-server-sqlnode \
	mysql-cluster-source \
	mysql-cluster-testsuite

echo Installed OK

# libdbd-mysql-perl has been updated to libmysqlclient18, but limited to a version
# so can't use libmysqlclient18-cluster. this means to install the client package
# or on most real world systems (almost anything with perl) we can't install
# the following packages:
# 	libmysqlclient18-cluster
# 	libmysqlclient-cluster-dev

