#!/bin/sh -e

apt-get -y install mysql-common libdbi-perl libdbd-mysql-perl

dpkg -i \
	libmysqlclient18-cluster_7.2.5-0.8_amd64.deb \
	libmysqlclient-cluster-dev_7.2.5-0.8_amd64.deb \
	libmysqld-cluster-dev_7.2.5-0.8_amd64.deb \
	libmysqld-cluster-pic_7.2.5-0.8_amd64.deb \
	libndbclient6_7.2.5-0.8_amd64.deb \
	libndbclient-dev_7.2.5-0.8_amd64.deb \
	mysql-client-cluster-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-client_7.2.5-0.8_all.deb \
	mysql-cluster-client-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-server-data_7.2.5-0.8_all.deb \
	mysql-cluster-server-data-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-server-mgmt_7.2.5-0.8_all.deb \
	mysql-cluster-server-mgmt-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-server-sql_7.2.5-0.8_all.deb \
	mysql-cluster-server-sql-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-server-sql-core-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-source-7.2_7.2.5-0.8_amd64.deb \
	mysql-cluster-testsuite-7.2_7.2.5-0.8_amd64.deb

