#!/bin/sh -e

SIGN_KEY=888012DD

PACKAGE_VERSION=`dpkg-parsechangelog | grep ^Version: | cut -d\  -f2`
VERSION=`echo $PACKAGE_VERSION | cut -d- -f1 | sed -e s/+dfsg//`
VERSION_MAJOR=`echo $VERSION | cut -d. -f1-2`
TARBALL=mysql-cluster-${VERSION_MAJOR}_${VERSION}+dfsg.orig.tar.gz
TARBALL_SYMLINK=mysql-cluster-${VERSION_MAJOR}_${VERSION}.orig.tar.gz
DIR=mysql-cluster-${VERSION}

# Build test options
# nocheck - skip testing (faster build)
# fulltest - very long testsuite
# leave both commented out for the normal test
export DEB_BUILD_OPTIONS=nocheck
#export DEB_BUILD_OPTIONS=fulltest

# Use ccache if available
if [ `which ccache` ]; then
	export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS} ccache"
fi

# Remove any old built files
scripts/clean

# Prepare build directory and compile
mkdir ${DIR}
cp -ar debian ${DIR}
(cd ${DIR} && debian/rules get-orig-source)
ln -fs ${TARBALL} ${TARBALL_SYMLINK}
tar -C ${DIR} --strip-components=1 -zxf ${TARBALL_SYMLINK}
(cd ${DIR} && dpkg-buildpackage -k${SIGN_KEY} 2>&1 | tee ../build.log)

# Cleanup and done
echo Built complete

