#!/bin/sh -e
#
# Because of versioned dependancies from other packages, we can't use our own
# versions of mysql-client (mysql-client-cluster) and libmysqlclient18 (libmysqlclient18-cluster)
# as versioned dependancies ignore virtual packages.
# This means the following packages although built cannot be installed:
# 	libmysqlclient18-cluster
# 	libmysqlclient-cluster-dev
#	mysql-client-cluster-7.2
#	mysql-client-core-cluster-7.2
#

sudo apt-get update

sudo apt-get -y install \
	libmysqld-cluster-pic \
	libmysqld-cluster-dev \
	libmysqlclient18-dev \
	libndbclient-dev \
	mysql-client \
	mysql-cluster-client \
	mysql-cluster-server-datanode \
	mysql-cluster-server-mgmtnode \
	mysql-cluster-server-sqlnode \
	mysql-cluster-source \
	mysql-cluster-testsuite \
	mysql-cluster-clusterj

echo Installed OK

