#!/bin/sh -e

sudo dpkg -P \
	mysql-common \
	mysql-cluster-common \
	libdbi-perl \
	libdbd-mysql-perl \
	libmysqlclient16 \
	libmysqlclient18 \
	libmysqlclient18-cluster \
	libmysqlclient-dev \
	libmysqlclient-cluster-dev \
	libmysqld-cluster-dev \
	libmysqld-cluster-pic \
	libndbclient6 \
	libndbclient-dev \
	mysql-client-cluster-7.2 \
	mysql-client-core-cluster-7.2 \
	mysql-cluster-client \
	mysql-cluster-client-7.2 \
	mysql-cluster-server-datanode \
	mysql-cluster-server-datanode-7.2 \
	mysql-cluster-server-mgmtnode \
	mysql-cluster-server-mgmtnode-7.2 \
	mysql-cluster-server-sqlnode \
	mysql-cluster-server-sqlnode-7.2 \
	mysql-cluster-server-sqlnode-core-7.2 \
	mysql-cluster-source-7.2 \
	mysql-cluster-testsuite-7.2 \
	mysql-cluster-clusterj \
	mysql-client \
	mysql-client-5.5 \
	mysql-server \
	mysql-server-5.5 \
	mysql-server-core-5.5

sudo apt-get -y autoremove

sudo killall -9 -w mysqld_safe mysqld

sudo rm -rf /etc/mysql /var/lib/mysql /var/log/mysql

echo Uninstalled OK

